[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
repo1-retention-diff=4
repo1-bundle=y
repo1-block=y
process-max=4
compress-type=zst
compress-level=6
start-fast=y
delta=y
archive-async=y
spool-path=/var/spool/pgbackrest
log-level-console=info
log-level-file=detail
log-path=/var/log/pgbackrest

[wms]
pg1-host=192.168.10.61
pg1-host-user=postgres
pg1-path=/var/lib/postgresql/17/wms
pg1-port=5432
pg2-host=192.168.10.60
pg2-host-user=postgres
pg2-path=/var/lib/postgresql/17/wms
pg2-port=5432
