global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
        labels: {instance: 'grafana'}
      - targets: ['192.168.10.61:9100']
        labels: {instance: 'pgsql-01'}
      - targets: ['192.168.10.60:9100']
        labels: {instance: 'pgsql-02'}

  - job_name: postgres
    static_configs:
      - targets: ['192.168.10.61:9187']
        labels: {instance: 'pgsql-01', role: 'primary'}
      - targets: ['192.168.10.60:9187']
        labels: {instance: 'pgsql-02', role: 'replica'}

  - job_name: patroni
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.10.61:8008', '192.168.10.60:8008']
